### ISSUE TITLE
best steez for links on landing page?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/roadrunner#138]
Wondering how best to style these links - buttons or just add link styling?

![screen shot 2016-03-07 at 8 53 33 pm](https://cloud.githubusercontent.com/assets/1307774/13592426/c39cfd5c-e4a6-11e5-8fdc-0af4fbe03123.png)

If you don't have time I can take another look but didn't want to delay getting the rest of this pr out :)

**Comment by gnakm** [comment]
@emilyville I like the link styling! Could we have them bold and underlined or similar to our grey hover links on vets.gov just so that they're distinct from the bullet points from goals and design principles?

For the content, could we have something like: 
**For Designers**
From prototyping to designing a look and feel, use these tools for designing websites and digital services specific to Veteran needs. Create experiences for your users that feel consistent across the VA. 

**For Developers**
Stand up quick prototypes or build whole websites. Save time and development cycles by reusing the code to efficiently update and launch tools and sites that are accessible and consistent for Veterans.

**Comment by gnakm** [comment]
This has been implemented.
