### ISSUE TITLE
Section Descriptions and 508 for Review

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#182]
Please proof these descriptions!

**Design** (Overview)

The Roadrunner Design Style Guide is a library of visual elements and snippets for designers and developers who want to successfully build their apps into existing Vets.gov projects. From branding to form components, Roadrunner has sections filled with design elements and information influenced by interviews and usability tests with our Veterans. While adapting the [US Web Design Standards](https://playbook.cio.gov/designstandards/visual-style/), Vets.gov branding and identity ...

**Branding**
With clarity and kindness as our priority, Vets.gov uses typography and color palettes that are usable and accessible for all users. Assuring a warm and welcoming feel, all headers are in Roboto Slab, a font described to be mechanical yet inviting. For clear and crisp read, Source Sans Pro can be found in copy and can be easy to read in all sizes and weight. We use the Web Content Accessibility Guidelines for Veterans of all ability and access to digital platforms. Texts and page elements the 4.5:1 color contrast to ensure legibility. 

**Templates**
As we get to know our users and stakeholders, our page layouts and UI components are continuing to evolve as we iterate our content and style. Vets.gov templates are still work in progress and can be used for reference in order to help keep the applications consistent and uniform. For better scan-ability, our UI components are broken down to be read from left to right and pages are composed with even balance of white space for clarity and legibility. 

**Navigation**

For easy and manageable navigation, breadcrumb links appear in the header of each content page to help visitors navigate and keep track of their location. For users with low vision and motor disability, our site is in tab control so that users who can move through the breadcrumb, links and text fields. 

**Forms**
_Coming Soon_

**Comment by maryannbrody** [comment]
Hey Gina!

These look great. I shortened them up a bit so they are just super clear and direct. Let me know what you think. 

Design (Overview)

Visual elements, UI components, and code snippets adapted from the [US Web Design Standards](https://playbook.cio.gov/designstandards/) to create consistency among all tools and products across Vets.gov platform. Built and maintained by the Digital Service at the Department of Veterans Affairs, Road Runner is guide for creating, beautiful, usable, and accessible Vets.gov designs. 

Branding
With clarity and kindness as our priority, Vets.gov uses typography and color palettes from the [US Web Design Standards](https://playbook.cio.gov/designstandards/) that are easy to read, usable, and accessible.

Templates
Vets.gov page layouts and UI components are continuing to evolve as we iterate our content and style. Vets.gov templates are still work in progress and can be used for reference in order to keep tools and products consistent. Designing for readability, UI components are broken down to be read from left to right and pages are composed with plenty of white space.

Navigation

Breadcrumb links appear in the header of each content page to help visitors navigate and keep track of their location. Users are also able to navigate through breadcrumbs, links, and text fields using tab control for accessibility. 

Forms
Coming Soon

**Comment by maryannbrody** [comment]
Hi @gnakm -- this is open and still assigned to me. Should it be? Let me know :-)

**Comment by gnakm** [comment]
@maryannbrody We're good on this. Coming now!
