### ISSUE TITLE
Collapsible Sidebar for Mobile

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/roadrunner#74]
![mobile getting started](https://cloud.githubusercontent.com/assets/13420618/13308803/9d2cda22-db44-11e5-88eb-43cc3c716edb.png)

@webinista @emilyville The 4 sections can be collapsible 

![mobile light grey collapsed](https://cloud.githubusercontent.com/assets/13420618/13309304/98fe6d6c-db49-11e5-9236-bf5131b17a72.png)
![mobile light grey expanded](https://cloud.githubusercontent.com/assets/13420618/13309306/9c712ab6-db49-11e5-9af3-68d697d455f9.png)

**Comment by webinista** [comment]
Are there any design changes to the desktop version after our meeting today? (i.e. going with an off-screen menu for all widths)

**Comment by gnakm** [comment]
@webinista I don't know what the current width is now but it would be great if we limit it to 80 characters. The biggest thing I got out of that meeting was scrolling side nav.

**Comment by emilyville** [comment]
Yeah, we didn't get so specific as widths. The changes I remember (should
have written this down, oops)
- scrolling in all cases / no fixed it absolute positioning
- side nav drawer for mobile
- for guide view, the header will change to no tabs on top, instead part of
  the side nav

**Comment by webinista** [comment]
@gnakm Can you send me the hamburger icon as an SVG file?

**Comment by webinista** [comment]
@gnakm @emilyville 

Changed the way the drawer works compared to how I think it was specced. It's difficult to make the navigation:
1. slide the entire page,
2. take up the full height of the content, and
3. keep the content and menu scrollable.

My impression from the mockups is that the behavior described above is what's intended. That is not, however, how it will work once #81 is merged. 

Instead the menu slides out partially over the content. In most of the "drawer" menus I've seen, where the entire page slides, there are either 
- two versions of the menu in the markup (heavy page weight) -- one for mobile, one for desktop _or_
- the menu covers the content with an overlay so that the user can't interact with the rest of the page.
- or, as [qz.com](http://qz.com/) does, the menu closes once the user scrolls the page.

We should probably discuss how and whether to iterate this drawer component at some point.
